services:
  neo4j:
    build:
      context: .
      dockerfile: Dockerfile.neo4j
    container_name: neo4jMaven
    ports:
      - "7474:7474"
      - "7687:7687"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7474 || exit 1"]
      interval: 5s
      retries: 5
    volumes:
      - neo4j-data:/data

  weaver:
    build:
      context: .
      dockerfile: Dockerfile.weaver
    container_name: goblinWeaver
    ports:
      - "8080:8080"
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      - NEO4J_URI=bolt://neo4jMaven:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=

volumes:
  neo4j-data: